/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: e3f3cdcd-bf73-4557-9cfe-de15475b1c01

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

def CD : Nat → Type
  | 0 => ℚ
  | n + 1 => CD n × CD n

instance instInhabitedCD (n : Nat) : Inhabited (CD n) :=
  match n with
  | 0 => inferInstanceAs (Inhabited ℚ)
  | n + 1 => @instInhabitedProd (CD n) (CD n) (instInhabitedCD n) (instInhabitedCD n)

instance instZeroCD (n : Nat) : Zero (CD n) :=
  match n with
  | 0 => inferInstanceAs (Zero ℚ)
  | n + 1 => @Prod.instZero (CD n) (CD n) (instZeroCD n) (instZeroCD n)

instance instOneCD (n : Nat) : One (CD n) :=
  match n with
  | 0 => inferInstanceAs (One ℚ)
  | n + 1 => @Prod.instOne (CD n) (CD n) (instOneCD n) (instOneCD n)

instance instAddCD (n : Nat) : Add (CD n) :=
  match n with
  | 0 => inferInstanceAs (Add ℚ)
  | n + 1 =>
    let _ : Add (CD n) := instAddCD n
    ⟨fun a b => (a.1 + b.1, a.2 + b.2)⟩

instance instNegCD (n : Nat) : Neg (CD n) :=
  match n with
  | 0 => inferInstanceAs (Neg ℚ)
  | n + 1 =>
    let _ : Neg (CD n) := instNegCD n
    ⟨fun a => (-a.1, -a.2)⟩

instance instSubCD (n : Nat) : Sub (CD n) :=
  match n with
  | 0 => inferInstanceAs (Sub ℚ)
  | n + 1 =>
    let _ : Sub (CD n) := instSubCD n
    ⟨fun a b => (a.1 - b.1, a.2 - b.2)⟩

instance instStarCD (n : Nat) : Star (CD n) :=
  match n with
  | 0 => inferInstanceAs (Star ℚ)
  | n + 1 =>
    let _ : Star (CD n) := instStarCD n
    let _ : Neg (CD n) := instNegCD n
    ⟨fun a => (star a.1, -a.2)⟩

instance instMulCD (n : Nat) : Mul (CD n) :=
  match n with
  | 0 => inferInstanceAs (Mul ℚ)
  | n + 1 =>
    let _ : Mul (CD n) := instMulCD n
    let _ : Add (CD n) := instAddCD n
    let _ : Sub (CD n) := instSubCD n
    let _ : Star (CD n) := instStarCD n
    ⟨fun a b => (a.1 * b.1 - star b.2 * a.2, b.2 * a.1 + a.2 * star b.1)⟩

def basis (n : Nat) (k : Nat) : CD n :=
  match n with
  | 0 => if k == 0 then 1 else 0
  | n + 1 =>
    if k < 2^n then
      (basis n k, 0)
    else
      (0, basis n (k - 2^n))

abbrev e (n : Nat) (k : Nat) : CD n := basis n k

def P1 (n : Nat) : CD n := e n 1 + e n 14
def Q1 (n : Nat) : CD n := e n 3 + e n 12

def IsBilateralZeroDivisor {α : Type} [Mul α] [Zero α] (a b : α) : Prop :=
  a * b = 0 ∧ b * a = 0

instance instAddCommGroupCD (n : Nat) : AddCommGroup (CD n) :=
  match n with
  | 0 => inferInstanceAs (AddCommGroup ℚ)
  | n + 1 =>
    let _ : AddCommGroup (CD n) := instAddCommGroupCD n
    @Prod.instAddCommGroup (CD n) (CD n) (instAddCommGroupCD n) (instAddCommGroupCD n)

theorem Pattern1_CD4 : IsBilateralZeroDivisor (P1 4) (Q1 4) := by
  constructor <;> norm_cast

def scalar (n : Nat) (q : ℚ) : CD n :=
  match n with
  | 0 => q
  | n + 1 => (scalar n q, 0)

instance (n : Nat) : Coe ℚ (CD n) := ⟨scalar n⟩

/-
The square of P1 in CD 4 is -2.
-/
lemma p1_sq : P1 4 * P1 4 = (-2 : ℚ) := by
  norm_cast

/-
The square of Q1 in CD 4 is -2.
-/
lemma q1_sq : Q1 4 * Q1 4 = (-2 : ℚ) := by
  norm_cast

/-
Scalars are self-adjoint and scalar addition is component-wise.
-/
lemma scalar_star (n : Nat) (q : ℚ) : star (scalar n q) = scalar n q := by
  induction' n with n ih generalizing q <;> simp_all +decide [ Star.star ];
  -- By definition of scalar multiplication, scalar (n+1) q is (scalar n q, 0).
  have h_scalar_succ : scalar (n + 1) q = (scalar n q, 0) := by
    rfl;
  -- By definition of scalar multiplication, scalar (n+1) q is (scalar n q, 0). Therefore, star (scalar (n+1) q) = (star (scalar n q), -0) = (scalar n q, 0) = scalar (n+1) q.
  rw [h_scalar_succ]
  simp [ih];
  -- Since -0 is equal to 0 in the rational numbers, we can conclude that (scalar n q, -0) = (scalar n q, 0).
  have h_neg_zero : (-0 : CD n) = 0 := by
    induction' n with n ih <;> simp +decide [ * ] at *;
    induction' n + 1 with n ih <;> simp +decide [ * ] at *;
    exact Prod.ext ih ih
  rw [h_neg_zero]

lemma scalar_add (n : Nat) (a b : ℚ) : scalar n (a + b) = scalar n a + scalar n b := by
  -- By definition of scalar multiplication, we can expand both sides.
  have h_expand : ∀ n : ℕ, ∀ a b : ℚ, (scalar n (a + b) : CD n) = (scalar n a + scalar n b : CD n) := by
    intro n a b;
    induction' n with n ih generalizing a b <;> simp +decide [ *, scalar ];
    -- By definition of addition in CD n, we have that (x, y) + (z, w) = (x + z, y + w).
    have h_add : ∀ (x y z w : CD n), (x, y) + (z, w) = (x + z, y + w) := by
      exact?;
    convert h_add _ _ _ _ |> Eq.symm using 1;
    have h_zero : ∀ (x : CD n), x + 0 = x := by
      induction' n with n ih;
      · exact?;
      · induction' n + 1 with n ih <;> simp_all +decide [ Prod.ext_iff ];
        exact fun x => Prod.ext ( ih _ ) ( ih _ );
    rw [ h_zero ];
  exact h_expand n a b

/-
The star of zero is zero in CD n.
-/
lemma star_zero_CD (n : Nat) : star (0 : CD n) = 0 := by
  convert scalar_star _ 0;
  · exact Eq.symm ( by exact Nat.recOn n ( by rfl ) fun n ih => by exact Prod.ext ih ( by rfl ) );
  · -- By definition of scalar, we have scalar n 0 = (0, 0) for any n > 0.
    induction' n with n ih;
    · rfl;
    · exact Prod.ext ih rfl

/-
Negative of zero is zero, and scalar preserves negation.
-/
lemma neg_zero_CD (n : Nat) : -(0 : CD n) = 0 := by
  induction' n with n ih;
  · norm_num +zetaDelta at *;
  · erw [ Prod.mk_inj ] ; aesop

lemma scalar_neg (n : Nat) (a : ℚ) : scalar n (-a) = -scalar n a := by
  induction' n with n ih;
  · exact?;
  · -- By definition of scalar multiplication in CD n+1, we have:
    have h_scalar_succ : scalar (n + 1) (-a) = (scalar n (-a), 0) := by
      exact?;
    have h_scalar_succ : scalar (n + 1) a = (scalar n a, 0) := by
      exact?
    simp_all +decide [ neg_eq_iff_add_eq_zero ];
    congr;
    exact?

/-
Zero multiplied by anything is zero, and anything multiplied by zero is zero.
-/
lemma zero_mul_CD (n : Nat) (x : CD n) : 0 * x = 0 := by
  -- By definition of multiplication in CD n, we have (0, 0) * (a, b) = (0*a - star b*0, b*0 + 0*star a).
  have h_mul_zero : ∀ n : ℕ, ∀ x y : CD n, 0 * x = 0 ∧ x * 0 = 0 := by
    intro n
    induction' n with n ih
    all_goals generalize_proofs at *;
    · aesop;
    · -- By definition of multiplication in CD (n + 1), we have:
      have h_mul_succ : ∀ x y : CD (n + 1), 0 * x = (0 * x.1 - star x.2 * 0, x.2 * 0 + 0 * star x.1) ∧ x * 0 = (x.1 * 0 - star 0 * x.2, 0 * x.1 + x.2 * star 0) := by
        exact fun x y => ⟨ rfl, rfl ⟩
      generalize_proofs at *; (
      -- By definition of star in CD n, we have star 0 = 0.
      have h_star_zero : ∀ n : ℕ, star (0 : CD n) = 0 := by
        exact?
      generalize_proofs at *; (
      simp_all +decide [ Prod.ext_iff ];
      -- By definition of subtraction and addition in CD n, we have 0 - 0 = 0 and 0 + 0 = 0.
      have h_sub_add : ∀ n : ℕ, (0 : CD n) - (0 : CD n) = 0 ∧ (0 : CD n) + (0 : CD n) = 0 := by
        intro n; exact ⟨by
        induction' n with n ih <;> simp +decide [ * ] at *; (
        exact Prod.ext ih ih), by
          induction' n with n ih
          all_goals generalize_proofs at *;
          exact?;
          exact Prod.ext ih ih⟩
      generalize_proofs at *; (
      exact Prod.ext ( h_sub_add n |>.1 ) ( h_sub_add n |>.2 ))))
  generalize_proofs at *; (
  exact h_mul_zero n x x |>.1)

lemma mul_zero_CD (n : Nat) (x : CD n) : x * 0 = 0 := by
  revert x;
  induction' n with n ih <;> norm_num [ instMulCD ] at *;
  intros x
  obtain ⟨a, b⟩ := x;
  convert congr_arg ( fun x : CD n × CD n => ( x.1, x.2 ) ) ( show ( a * 0 - star 0 * b, 0 * a + b * star 0 ) = ( 0, 0 ) from ?_ ) using 1;
  convert congr_arg ( fun x : CD n × CD n => ( x.1, x.2 ) ) ( show ( a * 0 - 0 * b, 0 * a + b * 0 ) = ( 0, 0 ) from ?_ ) using 1 ; simp +decide [ ih ];
  · rw [ star_zero_CD ] ; norm_num [ ih ] ;
  · have h_zero : ∀ (x : CD n), 0 * x = 0 := by
      exact?
    simp [h_zero, ih] at *;
    induction' n with n ih <;> norm_num [ instZeroCD ] at *;
    exact ⟨ Prod.mk_inj.mpr ⟨ ih.1, ih.1 ⟩, Prod.mk_inj.mpr ⟨ ih.2, ih.2 ⟩ ⟩

/-
Scalar subtraction is component-wise.
-/
lemma scalar_sub (n : Nat) (a b : ℚ) : scalar n (a - b) = scalar n a - scalar n b := by
  -- Rewrite subtraction as addition of the negative: $a - b = a + (-b)$.
  have h_sub : a - b = a + (-b) := by
    ring;
  rw [ h_sub, scalar_add, scalar_neg ];
  -- By definition of subtraction in the CD algebra, we have $x - y = x + (-y)$.
  have h_sub : ∀ x y : CD n, x - y = x + (-y) := by
    induction' n with n ih <;> simp_all +decide [ sub_eq_add_neg ];
    exact fun x y => Prod.ext ( ih _ _ ) ( ih _ _ );
  rw [ h_sub ]

/-
Scalar multiplication respects rational multiplication.
-/
lemma scalar_mul_scalar (n : Nat) (a b : ℚ) : scalar n a * scalar n b = scalar n (a * b) := by
  induction' n with n ih generalizing a b;
  · exact?;
  · -- By definition of scalar multiplication in CD (n + 1), we have:
    have h_scalar_mul : scalar (n + 1) a * scalar (n + 1) b = (scalar n a * scalar n b, 0) := by
      -- By definition of scalar multiplication in CD (n + 1), we have that scalar (n + 1) a * scalar (n + 1) b = (scalar n a * scalar n b, 0).
      have h_scalar_mul : scalar (n + 1) a * scalar (n + 1) b = (scalar n a * scalar n b - star (0 : CD n) * 0, 0 * scalar n a + 0 * star (scalar n b)) := by
        exact?;
      convert h_scalar_mul using 1 ; norm_num [ star_zero_CD, zero_mul_CD, mul_zero_CD ];
      -- In the context of CD n, subtraction and addition of zero are defined as component-wise operations.
      have h_zero : ∀ x : CD n, x - 0 = x ∧ 0 + x = x := by
        induction' n with n ih;
        · aesop;
        · induction' n + 1 with n ih <;> simp_all +decide [ Prod.ext_iff ];
          exact fun x => ⟨ Prod.ext ( ih _ |>.1 ) ( ih _ |>.1 ), Prod.ext ( ih _ |>.2 ) ( ih _ |>.2 ) ⟩;
      rw [ h_zero _ |>.1, h_zero _ |>.2 ];
    aesop

/-
The scalar injection of 0 is the zero element.
-/
lemma scalar_zero (n : Nat) : scalar n 0 = 0 := by
  induction n with
  | zero => rfl
  | succ n ih =>
    simp [scalar, ih]
    rfl

/-
Scalars commute with all elements in CD n.
-/
lemma scalar_comm (n : Nat) (q : ℚ) (x : CD n) : scalar n q * x = x * scalar n q := by
  -- We proceed by induction on $n$.
  induction' n with n ih;
  · exact mul_comm q x;
  · cases x ; simp_all +decide [ scalar, Prod.ext_iff ];
    erw [ Prod.mk_inj ];
    have h_star_zero : star (0 : CD n) = 0 := by
      exact?
    simp [h_star_zero] at *;
    -- By the induction hypothesis, we know that scalar n q * x = x * scalar n q for any x in CD n.
    have h_ind : ∀ x : CD n, scalar n q * x = x * scalar n q := by
      assumption;
    rw [ show Star.star ( scalar n q ) = scalar n q from ?_ ];
    · have h_zero_mul : ∀ x : CD n, 0 * x = 0 := by
        exact?
      have h_mul_zero : ∀ x : CD n, x * 0 = 0 := by
        exact?
      simp [h_zero_mul, h_mul_zero] at *;
      simp +decide [ h_ind, add_comm ];
      have h_add_comm : ∀ x y : CD n, x + y = y + x := by
        -- By the induction hypothesis, we know that addition in CD n is commutative.
        have h_add_comm : ∀ x y : CD n, x + y = y + x := by
          have h_ind : ∀ n, ∀ x y : CD n, x + y = y + x := by
            intro n; induction' n with n ih <;> simp_all +decide [ add_comm ] ;
            exact fun x y => Prod.ext ( ih _ _ ) ( ih _ _ )
          exact h_ind n;
        exact h_add_comm
      simp [h_add_comm] at *;
    · exact?